/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FoodRouteImport } from './routes/food'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReportListingRouteImport } from './routes/report-listing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellerHandbookRouteImport } from './routes/seller-handbook'
import { Route as ShortLetsRouteImport } from './routes/short-lets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentHousingRouteImport } from './routes/student-housing'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as VerifiedStoresRouteImport } from './routes/verified-stores'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminFoodOrdersRouteImport } from './routes/admin.food-orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as BuyerBecomeSellerRouteImport } from './routes/buyer.become-seller'
import { Route as BuyerCartRouteImport } from './routes/buyer.cart'
import { Route as BuyerCheckoutRouteImport } from './routes/buyer.checkout'
import { Route as BuyerFoodOrdersRouteImport } from './routes/buyer.food-orders'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer.notifications'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerReviewsRouteImport } from './routes/buyer.reviews'
import { Route as BuyerSettingsRouteImport } from './routes/buyer.settings'
import { Route as BuyerSupportRouteImport } from './routes/buyer.support'
import { Route as BuyerWishlistRouteImport } from './routes/buyer.wishlist'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as FoodRestaurantIdRouteImport } from './routes/food.$restaurantId'
import { Route as FoodCartRouteImport } from './routes/food.cart'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ReelsItemIdRouteImport } from './routes/reels.$itemId'
import { Route as ReelsProductIdRouteImport } from './routes/reels.$productId'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SellerFollowersRouteImport } from './routes/seller.followers'
import { Route as SellerNotificationsRouteImport } from './routes/seller.notifications'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerPerformanceRouteImport } from './routes/seller.performance'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerReviewsRouteImport } from './routes/seller.reviews'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerUploadRouteImport } from './routes/seller.upload'
import { Route as SellerWalletRouteImport } from './routes/seller.wallet'
import { Route as SettingsDeleteAccountRouteImport } from './routes/settings.delete-account'
import { Route as StoreSellerIdRouteImport } from './routes/store.$sellerId'
import { Route as FoodTrackOrderIdRouteImport } from './routes/food.track.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportListingRoute = ReportListingRouteImport.update({
  id: '/report-listing',
  path: '/report-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerHandbookRoute = SellerHandbookRouteImport.update({
  id: '/seller-handbook',
  path: '/seller-handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortLetsRoute = ShortLetsRouteImport.update({
  id: '/short-lets',
  path: '/short-lets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHousingRoute = StudentHousingRouteImport.update({
  id: '/student-housing',
  path: '/student-housing',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedStoresRoute = VerifiedStoresRouteImport.update({
  id: '/verified-stores',
  path: '/verified-stores',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodOrdersRoute = AdminFoodOrdersRouteImport.update({
  id: '/food-orders',
  path: '/food-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerBecomeSellerRoute = BuyerBecomeSellerRouteImport.update({
  id: '/become-seller',
  path: '/become-seller',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCartRoute = BuyerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCheckoutRoute = BuyerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerFoodOrdersRoute = BuyerFoodOrdersRouteImport.update({
  id: '/food-orders',
  path: '/food-orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerReviewsRoute = BuyerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerSettingsRoute = BuyerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerSupportRoute = BuyerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerWishlistRoute = BuyerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => BuyerRoute,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRestaurantIdRoute = FoodRestaurantIdRouteImport.update({
  id: '/$restaurantId',
  path: '/$restaurantId',
  getParentRoute: () => FoodRoute,
} as any)
const FoodCartRoute = FoodCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => FoodRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsItemIdRoute = ReelsItemIdRouteImport.update({
  id: '/reels/$itemId',
  path: '/reels/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsProductIdRoute = ReelsProductIdRouteImport.update({
  id: '/reels/$productId',
  path: '/reels/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const SellerFollowersRoute = SellerFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNotificationsRoute = SellerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPerformanceRoute = SellerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerUploadRoute = SellerUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => SellerRoute,
} as any)
const SellerWalletRoute = SellerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SellerRoute,
} as any)
const SettingsDeleteAccountRoute = SettingsDeleteAccountRouteImport.update({
  id: '/settings/delete-account',
  path: '/settings/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSellerIdRoute = StoreSellerIdRouteImport.update({
  id: '/store/$sellerId',
  path: '/store/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodTrackOrderIdRoute = FoodTrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => FoodRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/blog': typeof BlogRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/careers': typeof CareersRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help-center': typeof HelpCenterRoute
  '/hotels': typeof HotelsRoute
  '/investors': typeof InvestorsRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/report-listing': typeof ReportListingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/seller': typeof SellerRouteWithChildren
  '/seller-handbook': typeof SellerHandbookRoute
  '/short-lets': typeof ShortLetsRoute
  '/signup': typeof SignupRoute
  '/student-housing': typeof StudentHousingRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/verified-stores': typeof VerifiedStoresRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/food-orders': typeof AdminFoodOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/buyer/become-seller': typeof BuyerBecomeSellerRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/food-orders': typeof BuyerFoodOrdersRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/reviews': typeof BuyerReviewsRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/support': typeof BuyerSupportRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/food/$restaurantId': typeof FoodRestaurantIdRoute
  '/food/cart': typeof FoodCartRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/reels/$itemId': typeof ReelsItemIdRoute
  '/reels/$productId': typeof ReelsProductIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/followers': typeof SellerFollowersRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/performance': typeof SellerPerformanceRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/upload': typeof SellerUploadRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/store/$sellerId': typeof StoreSellerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/food/track/$orderId': typeof FoodTrackOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/blog': typeof BlogRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/careers': typeof CareersRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help-center': typeof HelpCenterRoute
  '/hotels': typeof HotelsRoute
  '/investors': typeof InvestorsRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/report-listing': typeof ReportListingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/seller-handbook': typeof SellerHandbookRoute
  '/short-lets': typeof ShortLetsRoute
  '/signup': typeof SignupRoute
  '/student-housing': typeof StudentHousingRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/verified-stores': typeof VerifiedStoresRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/food-orders': typeof AdminFoodOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/buyer/become-seller': typeof BuyerBecomeSellerRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/food-orders': typeof BuyerFoodOrdersRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/reviews': typeof BuyerReviewsRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/support': typeof BuyerSupportRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/food/$restaurantId': typeof FoodRestaurantIdRoute
  '/food/cart': typeof FoodCartRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/reels/$itemId': typeof ReelsItemIdRoute
  '/reels/$productId': typeof ReelsProductIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/followers': typeof SellerFollowersRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/performance': typeof SellerPerformanceRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/upload': typeof SellerUploadRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/store/$sellerId': typeof StoreSellerIdRoute
  '/admin': typeof AdminIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/food/track/$orderId': typeof FoodTrackOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/blog': typeof BlogRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/careers': typeof CareersRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help-center': typeof HelpCenterRoute
  '/hotels': typeof HotelsRoute
  '/investors': typeof InvestorsRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/report-listing': typeof ReportListingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/seller': typeof SellerRouteWithChildren
  '/seller-handbook': typeof SellerHandbookRoute
  '/short-lets': typeof ShortLetsRoute
  '/signup': typeof SignupRoute
  '/student-housing': typeof StudentHousingRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/verified-stores': typeof VerifiedStoresRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/food-orders': typeof AdminFoodOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/buyer/become-seller': typeof BuyerBecomeSellerRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/food-orders': typeof BuyerFoodOrdersRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/buyer/reviews': typeof BuyerReviewsRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/support': typeof BuyerSupportRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/food/$restaurantId': typeof FoodRestaurantIdRoute
  '/food/cart': typeof FoodCartRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/reels/$itemId': typeof ReelsItemIdRoute
  '/reels/$productId': typeof ReelsProductIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/followers': typeof SellerFollowersRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/performance': typeof SellerPerformanceRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/upload': typeof SellerUploadRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/store/$sellerId': typeof StoreSellerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/food/track/$orderId': typeof FoodTrackOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/blog'
    | '/bulk-orders'
    | '/buyer'
    | '/careers'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/food'
    | '/forgot-password'
    | '/help-center'
    | '/hotels'
    | '/investors'
    | '/list-property'
    | '/login'
    | '/press'
    | '/privacy'
    | '/refund-policy'
    | '/report-listing'
    | '/reset-password'
    | '/returns'
    | '/search'
    | '/seller'
    | '/seller-handbook'
    | '/short-lets'
    | '/signup'
    | '/student-housing'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/verified-stores'
    | '/verify-email'
    | '/admin/disputes'
    | '/admin/food-orders'
    | '/admin/products'
    | '/admin/restaurants'
    | '/admin/sellers'
    | '/admin/support'
    | '/admin/withdrawals'
    | '/auth/callback'
    | '/buyer/become-seller'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/food-orders'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reviews'
    | '/buyer/settings'
    | '/buyer/support'
    | '/buyer/wishlist'
    | '/category/$categoryId'
    | '/food/$restaurantId'
    | '/food/cart'
    | '/product/$productId'
    | '/reels/$itemId'
    | '/reels/$productId'
    | '/seller/analytics'
    | '/seller/followers'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/performance'
    | '/seller/products'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/upload'
    | '/seller/wallet'
    | '/settings/delete-account'
    | '/store/$sellerId'
    | '/admin/'
    | '/buyer/'
    | '/seller/'
    | '/food/track/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/blog'
    | '/bulk-orders'
    | '/careers'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/food'
    | '/forgot-password'
    | '/help-center'
    | '/hotels'
    | '/investors'
    | '/list-property'
    | '/login'
    | '/press'
    | '/privacy'
    | '/refund-policy'
    | '/report-listing'
    | '/reset-password'
    | '/returns'
    | '/search'
    | '/seller-handbook'
    | '/short-lets'
    | '/signup'
    | '/student-housing'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/verified-stores'
    | '/verify-email'
    | '/admin/disputes'
    | '/admin/food-orders'
    | '/admin/products'
    | '/admin/restaurants'
    | '/admin/sellers'
    | '/admin/support'
    | '/admin/withdrawals'
    | '/auth/callback'
    | '/buyer/become-seller'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/food-orders'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reviews'
    | '/buyer/settings'
    | '/buyer/support'
    | '/buyer/wishlist'
    | '/category/$categoryId'
    | '/food/$restaurantId'
    | '/food/cart'
    | '/product/$productId'
    | '/reels/$itemId'
    | '/reels/$productId'
    | '/seller/analytics'
    | '/seller/followers'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/performance'
    | '/seller/products'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/upload'
    | '/seller/wallet'
    | '/settings/delete-account'
    | '/store/$sellerId'
    | '/admin'
    | '/buyer'
    | '/seller'
    | '/food/track/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/blog'
    | '/bulk-orders'
    | '/buyer'
    | '/careers'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/food'
    | '/forgot-password'
    | '/help-center'
    | '/hotels'
    | '/investors'
    | '/list-property'
    | '/login'
    | '/press'
    | '/privacy'
    | '/refund-policy'
    | '/report-listing'
    | '/reset-password'
    | '/returns'
    | '/search'
    | '/seller'
    | '/seller-handbook'
    | '/short-lets'
    | '/signup'
    | '/student-housing'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/verified-stores'
    | '/verify-email'
    | '/admin/disputes'
    | '/admin/food-orders'
    | '/admin/products'
    | '/admin/restaurants'
    | '/admin/sellers'
    | '/admin/support'
    | '/admin/withdrawals'
    | '/auth/callback'
    | '/buyer/become-seller'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/food-orders'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reviews'
    | '/buyer/settings'
    | '/buyer/support'
    | '/buyer/wishlist'
    | '/category/$categoryId'
    | '/food/$restaurantId'
    | '/food/cart'
    | '/product/$productId'
    | '/reels/$itemId'
    | '/reels/$productId'
    | '/seller/analytics'
    | '/seller/followers'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/performance'
    | '/seller/products'
    | '/seller/reviews'
    | '/seller/settings'
    | '/seller/upload'
    | '/seller/wallet'
    | '/settings/delete-account'
    | '/store/$sellerId'
    | '/admin/'
    | '/buyer/'
    | '/seller/'
    | '/food/track/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  BlogRoute: typeof BlogRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  CareersRoute: typeof CareersRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  FoodRoute: typeof FoodRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpCenterRoute: typeof HelpCenterRoute
  HotelsRoute: typeof HotelsRoute
  InvestorsRoute: typeof InvestorsRoute
  ListPropertyRoute: typeof ListPropertyRoute
  LoginRoute: typeof LoginRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReportListingRoute: typeof ReportListingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  SearchRoute: typeof SearchRoute
  SellerRoute: typeof SellerRouteWithChildren
  SellerHandbookRoute: typeof SellerHandbookRoute
  ShortLetsRoute: typeof ShortLetsRoute
  SignupRoute: typeof SignupRoute
  StudentHousingRoute: typeof StudentHousingRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  VerifiedStoresRoute: typeof VerifiedStoresRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ReelsItemIdRoute: typeof ReelsItemIdRoute
  ReelsProductIdRoute: typeof ReelsProductIdRoute
  SettingsDeleteAccountRoute: typeof SettingsDeleteAccountRoute
  StoreSellerIdRoute: typeof StoreSellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-listing': {
      id: '/report-listing'
      path: '/report-listing'
      fullPath: '/report-listing'
      preLoaderRoute: typeof ReportListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-handbook': {
      id: '/seller-handbook'
      path: '/seller-handbook'
      fullPath: '/seller-handbook'
      preLoaderRoute: typeof SellerHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-lets': {
      id: '/short-lets'
      path: '/short-lets'
      fullPath: '/short-lets'
      preLoaderRoute: typeof ShortLetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-housing': {
      id: '/student-housing'
      path: '/student-housing'
      fullPath: '/student-housing'
      preLoaderRoute: typeof StudentHousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-stores': {
      id: '/verified-stores'
      path: '/verified-stores'
      fullPath: '/verified-stores'
      preLoaderRoute: typeof VerifiedStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/food-orders': {
      id: '/admin/food-orders'
      path: '/food-orders'
      fullPath: '/admin/food-orders'
      preLoaderRoute: typeof AdminFoodOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/become-seller': {
      id: '/buyer/become-seller'
      path: '/become-seller'
      fullPath: '/buyer/become-seller'
      preLoaderRoute: typeof BuyerBecomeSellerRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/cart': {
      id: '/buyer/cart'
      path: '/cart'
      fullPath: '/buyer/cart'
      preLoaderRoute: typeof BuyerCartRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/checkout': {
      id: '/buyer/checkout'
      path: '/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof BuyerCheckoutRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/food-orders': {
      id: '/buyer/food-orders'
      path: '/food-orders'
      fullPath: '/buyer/food-orders'
      preLoaderRoute: typeof BuyerFoodOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/reviews': {
      id: '/buyer/reviews'
      path: '/reviews'
      fullPath: '/buyer/reviews'
      preLoaderRoute: typeof BuyerReviewsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/settings': {
      id: '/buyer/settings'
      path: '/settings'
      fullPath: '/buyer/settings'
      preLoaderRoute: typeof BuyerSettingsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/support': {
      id: '/buyer/support'
      path: '/support'
      fullPath: '/buyer/support'
      preLoaderRoute: typeof BuyerSupportRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/wishlist': {
      id: '/buyer/wishlist'
      path: '/wishlist'
      fullPath: '/buyer/wishlist'
      preLoaderRoute: typeof BuyerWishlistRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$restaurantId': {
      id: '/food/$restaurantId'
      path: '/$restaurantId'
      fullPath: '/food/$restaurantId'
      preLoaderRoute: typeof FoodRestaurantIdRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/cart': {
      id: '/food/cart'
      path: '/cart'
      fullPath: '/food/cart'
      preLoaderRoute: typeof FoodCartRouteImport
      parentRoute: typeof FoodRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/$itemId': {
      id: '/reels/$itemId'
      path: '/reels/$itemId'
      fullPath: '/reels/$itemId'
      preLoaderRoute: typeof ReelsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/$productId': {
      id: '/reels/$productId'
      path: '/reels/$productId'
      fullPath: '/reels/$productId'
      preLoaderRoute: typeof ReelsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/followers': {
      id: '/seller/followers'
      path: '/followers'
      fullPath: '/seller/followers'
      preLoaderRoute: typeof SellerFollowersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/notifications': {
      id: '/seller/notifications'
      path: '/notifications'
      fullPath: '/seller/notifications'
      preLoaderRoute: typeof SellerNotificationsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/performance': {
      id: '/seller/performance'
      path: '/performance'
      fullPath: '/seller/performance'
      preLoaderRoute: typeof SellerPerformanceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/upload': {
      id: '/seller/upload'
      path: '/upload'
      fullPath: '/seller/upload'
      preLoaderRoute: typeof SellerUploadRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/wallet': {
      id: '/seller/wallet'
      path: '/wallet'
      fullPath: '/seller/wallet'
      preLoaderRoute: typeof SellerWalletRouteImport
      parentRoute: typeof SellerRoute
    }
    '/settings/delete-account': {
      id: '/settings/delete-account'
      path: '/settings/delete-account'
      fullPath: '/settings/delete-account'
      preLoaderRoute: typeof SettingsDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$sellerId': {
      id: '/store/$sellerId'
      path: '/store/$sellerId'
      fullPath: '/store/$sellerId'
      preLoaderRoute: typeof StoreSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/track/$orderId': {
      id: '/food/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/food/track/$orderId'
      preLoaderRoute: typeof FoodTrackOrderIdRouteImport
      parentRoute: typeof FoodRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminFoodOrdersRoute: typeof AdminFoodOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDisputesRoute: AdminDisputesRoute,
  AdminFoodOrdersRoute: AdminFoodOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BuyerRouteChildren {
  BuyerBecomeSellerRoute: typeof BuyerBecomeSellerRoute
  BuyerCartRoute: typeof BuyerCartRoute
  BuyerCheckoutRoute: typeof BuyerCheckoutRoute
  BuyerFoodOrdersRoute: typeof BuyerFoodOrdersRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerOrdersRoute: typeof BuyerOrdersRoute
  BuyerReviewsRoute: typeof BuyerReviewsRoute
  BuyerSettingsRoute: typeof BuyerSettingsRoute
  BuyerSupportRoute: typeof BuyerSupportRoute
  BuyerWishlistRoute: typeof BuyerWishlistRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerBecomeSellerRoute: BuyerBecomeSellerRoute,
  BuyerCartRoute: BuyerCartRoute,
  BuyerCheckoutRoute: BuyerCheckoutRoute,
  BuyerFoodOrdersRoute: BuyerFoodOrdersRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerOrdersRoute: BuyerOrdersRoute,
  BuyerReviewsRoute: BuyerReviewsRoute,
  BuyerSettingsRoute: BuyerSettingsRoute,
  BuyerSupportRoute: BuyerSupportRoute,
  BuyerWishlistRoute: BuyerWishlistRoute,
  BuyerIndexRoute: BuyerIndexRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface FoodRouteChildren {
  FoodRestaurantIdRoute: typeof FoodRestaurantIdRoute
  FoodCartRoute: typeof FoodCartRoute
  FoodTrackOrderIdRoute: typeof FoodTrackOrderIdRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodRestaurantIdRoute: FoodRestaurantIdRoute,
  FoodCartRoute: FoodCartRoute,
  FoodTrackOrderIdRoute: FoodTrackOrderIdRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

interface SellerRouteChildren {
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerFollowersRoute: typeof SellerFollowersRoute
  SellerNotificationsRoute: typeof SellerNotificationsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPerformanceRoute: typeof SellerPerformanceRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerUploadRoute: typeof SellerUploadRoute
  SellerWalletRoute: typeof SellerWalletRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerFollowersRoute: SellerFollowersRoute,
  SellerNotificationsRoute: SellerNotificationsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPerformanceRoute: SellerPerformanceRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerUploadRoute: SellerUploadRoute,
  SellerWalletRoute: SellerWalletRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  BlogRoute: BlogRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  BuyerRoute: BuyerRouteWithChildren,
  CareersRoute: CareersRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  FoodRoute: FoodRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpCenterRoute: HelpCenterRoute,
  HotelsRoute: HotelsRoute,
  InvestorsRoute: InvestorsRoute,
  ListPropertyRoute: ListPropertyRoute,
  LoginRoute: LoginRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReportListingRoute: ReportListingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  SearchRoute: SearchRoute,
  SellerRoute: SellerRouteWithChildren,
  SellerHandbookRoute: SellerHandbookRoute,
  ShortLetsRoute: ShortLetsRoute,
  SignupRoute: SignupRoute,
  StudentHousingRoute: StudentHousingRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  VerifiedStoresRoute: VerifiedStoresRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ReelsItemIdRoute: ReelsItemIdRoute,
  ReelsProductIdRoute: ReelsProductIdRoute,
  SettingsDeleteAccountRoute: SettingsDeleteAccountRoute,
  StoreSellerIdRoute: StoreSellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
